site_name: Pydantic Validation 中文文档
site_description: 使用 Python 类型提示进行数据验证
copyright: <a href="https://github.com/oaixnah" target="_blank">译者 oaixnah</a>
strict: true
site_url: https://docs.pydantic.dev/

theme:
  name: 'material'
  language: zh
  palette:
    - media: "(prefers-color-scheme)"
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-auto
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: "Switch to system preference"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  logo: 'logo-white.svg'
  favicon: 'favicon.png'
  custom_dir: docs/theme

repo_name: pydantic/pydantic
repo_url: https://github.com/pydantic/pydantic
extra:
  analytics:
    provider: !ENV ANALYTICS_PROVIDER
    property: !ENV GOOGLE_ANALYTICS_KEY
    clarity: !ENV CLARITY_PROJECT_ID
  version:
    alias: true
    provider: mike

extra_css:
  - 'extra/terminal.css'
  - 'extra/tweaks.css'

nav:
  - 快速开始:
      - Welcome to Pydantic: index.md
      - Why use Pydantic: why.md
      - Help with Pydantic: help_with_pydantic.md
      - Installation: install.md
      - Migration Guide: migration.md
      - Version Policy: version-policy.md
      - Contributing: contributing.md
  - 概念:
      - Models: concepts/models.md
      - Fields: concepts/fields.md
      - JSON Schema: concepts/json_schema.md
      - JSON: concepts/json.md
      - Types: concepts/types.md
      - Unions: concepts/unions.md
      - Alias: concepts/alias.md
      - Configuration: concepts/config.md
      - Serialization: concepts/serialization.md
      - Validators: concepts/validators.md
      - Dataclasses: concepts/dataclasses.md
      - Forward Annotations: concepts/forward_annotations.md
      - Strict Mode: concepts/strict_mode.md
      - Type Adapter: concepts/type_adapter.md
      - Validation Decorator: concepts/validation_decorator.md
      - Conversion Table: concepts/conversion_table.md
      - Settings Management: concepts/pydantic_settings.md
      - Performance: concepts/performance.md
      - Experimental: concepts/experimental.md
  - API 参考:
      - Pydantic:
          - BaseModel: api/base_model.md
          - RootModel: api/root_model.md
          - Pydantic Dataclasses: api/dataclasses.md
          - TypeAdapter: api/type_adapter.md
          - Validate Call: api/validate_call.md
          - Fields: api/fields.md
          - Aliases: api/aliases.md
          - Configuration: api/config.md
          - JSON Schema: api/json_schema.md
          - Errors: api/errors.md
          - Functional Validators: api/functional_validators.md
          - Functional Serializers: api/functional_serializers.md
          - Standard Library Types: api/standard_library_types.md
          - Pydantic Types: api/types.md
          - Network Types: api/networks.md
          - Version Information: api/version.md
          - Annotated Handlers: api/annotated_handlers.md
          - Experimental: api/experimental.md
      - Pydantic Core:
          - pydantic_core: api/pydantic_core.md
          - pydantic_core.core_schema: api/pydantic_core_schema.md
      - Pydantic Settings: api/pydantic_settings.md
      - Pydantic Extra Types:
          - Color: api/pydantic_extra_types_color.md
          - Country: api/pydantic_extra_types_country.md
          - Payment: api/pydantic_extra_types_payment.md
          - Phone Numbers: api/pydantic_extra_types_phone_numbers.md
          - Routing Numbers: api/pydantic_extra_types_routing_numbers.md
          - Coordinate: api/pydantic_extra_types_coordinate.md
          - Mac Address: api/pydantic_extra_types_mac_address.md
          - ISBN: api/pydantic_extra_types_isbn.md
          - Pendulum: api/pydantic_extra_types_pendulum_dt.md
          - Currency: api/pydantic_extra_types_currency_code.md
          - Language: api/pydantic_extra_types_language_code.md
          - Script Code: api/pydantic_extra_types_script_code.md
          - Semantic Version: api/pydantic_extra_types_semantic_version.md
          - Timezone Name: api/pydantic_extra_types_timezone_name.md
  - 内部实现:
      - Architecture: internals/architecture.md
      - Resolving Annotations: internals/resolving_annotations.md
  - 示例:
      - Validating File Data: examples/files.md
      - Web and API Requests: examples/requests.md
      - Queues: examples/queues.md
      - Databases: examples/orms.md
      - Custom Validators: examples/custom_validators.md
  - 错误信息:
      - Error Handling: errors/errors.md
      - Validation Errors: errors/validation_errors.md
      - Usage Errors: errors/usage_errors.md
  - 集成:
      - Pydantic Logfire: integrations/logfire.md
      - LLMs: integrations/llms.md
      - 开发工具:
          - Mypy: integrations/mypy.md
          - Pyrefly: integrations/pyrefly.md
          - PyCharm: integrations/pycharm.md
          - Hypothesis: integrations/hypothesis.md
          - Visual Studio Code: integrations/visual_studio_code.md
          - datamodel-code-generator: integrations/datamodel_code_generator.md
          - devtools: integrations/devtools.md
          - Rich: integrations/rich.md
          - Linting: integrations/linting.md
          - Documentation: integrations/documentation.md
      - 生产工具:
          - AWS Lambda: integrations/aws_lambda.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true

hooks:
  - 'docs/plugins/main.py'

plugins:
  - mike:
      alias_type: copy
      canonical_version: latest
  - search
  - exclude:
      glob:
        - '*_en.md'
        - plugins/*
  - mkdocstrings:
      handlers:
        python:
          paths: [ . ]  # see also: build-docs.sh
          options:
            members_order: source
            separate_signature: true
            filters: [ "!^_" ]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
          import:
            - url: https://docs.python.org/3/objects.inv
              domains: [ py, std ]
            - url: https://typing-extensions.readthedocs.io/en/latest/objects.inv
