name: Publish Documentation

on:
  push:
    tags:
      - '*.*'

jobs:
  publish:
    # Compare with the docs-build job in .github/workflows/ci.yml
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Extract version from tag
        id: extract_version
        run: |
          # 从 tag 中提取 MAJOR.MINOR 版本号
          VERSION_MAJOR_MINOR=$(echo ${{ github.ref_name }} | sed 's/\.[^.]*$//')
          echo "VERSION_MAJOR_MINOR=$VERSION_MAJOR_MINOR" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION_MAJOR_MINOR from tag: ${{ github.ref_name }}"

      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mike mkdocs-material mkdocs-exclude mkdocs-llmstxt mkdocstrings-python pydantic pydantic-core pydantic-extra-types pydantic-settings
      - run: mike deploy ${{ steps.extract_version.outputs.VERSION_MAJOR_MINOR }} latest --update-aliases --push