name: Publish Documentation

on:
  push:
    tags:
      - '*.*'

jobs:
  publish:
    # Compare with the docs-build job in .github/workflows/ci.yml
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'

      - run: uv sync

      # Taken from docs-build.sh
      - name: Prepare shortcuts for extra modules
        run: |
          ln -s .venv/lib/python*/site-packages/pydantic_core pydantic_core
          ln -s .venv/lib/python*/site-packages/pydantic_settings pydantic_settings
          ln -s .venv/lib/python*/site-packages/pydantic_extra_types pydantic_extra_types

      - run: uv run mike deploy ${{ github.ref_name }} latest --update-aliases --push